version: "3.8"
services:
    db:
      image: mysql:5.7
      ports:
        - '3306:3306'
      networks:
        - backend
      volumes:
        # PERS ISTENCIA DE DATOS EN VOLUMEN my-db 
        - my-db:/var/lib/mysql
      deploy:
        placement:
          constraints:
            - "node.role==manager"
        replicas: 5
        update_config:
          parallelism: 5
          delay: 10s
        restart_policy:
          condition: on-failure
      environment:
        MYSQL_DATABASE: 'cfe_traccar'
        MYSQL_USER: 'dhapsa'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'

volumes:
    my-db:

networks:
   backend: